/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataInput: typeof import('./components/DataInput.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    PostgresReportPicker: typeof import('./components/PostgresReportPicker.vue')['default']
    ReportUrlFetcher: typeof import('./components/ReportUrlFetcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
